config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  ###
  # Static pages
  #

  controller :pages do
    get 'home'
    get 'help'
    get 'info'
    get 'data'
  end

  ###
  # Account
  #

  get 'register', to: redirect('accounts/new'),  as: :register
  get 'login',    to: redirect('sessions/new'),  as: :login
  get 'logout',   to: 'sessions#destroy',        as: :logout

  resources :accounts, except: %i[index show]

  get 'accounts/confirm_email/:token' =>
      'accounts#confirm_email', as: :confirm_email

  get 'accounts/confirm_jabber/:token' =>
      'accounts#confirm_jabber', as: :confirm_jabber

  get 'accounts/repeat_email_confirmation' =>
      'accounts#repeat_email_confirmation', as: :repeat_email_confirmation

  get 'accounts/repeat_jabber_confirmation' =>
      'accounts#repeat_jabber_confirmation', as: :repeat_jabber_confirmation

  match 'accounts/reset_password' =>
        'accounts#reset_password', via: %i[get post], as: :reset_password

  ###
  # Others
  #

  resources :contacts, only: %i[new create]
  resources :sessions, only: %i[new create destroy]

  get 'locale/change/:lang', to: 'locale#change', as: :change_locale

  resources :forums, except: :show do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :letters, except: :show do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :letter_items, except: :show do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :reader_sets, as: :reader, only: [] do
    member do
      patch :change_status
    end
  end

  resources :mailer_sets, as: :mailer, only: [] do
    member do
      patch :change_status
    end
  end

  ###
  # Sidekiq monitoring
  #

  # TODO
  # require 'sidekiq/web' # TODO: security (password)
  # mount Sidekiq::Web => '/sidekiq'

  # if Rails.env.production? # TODO
  #   Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  #     ActiveSupport::SecurityUtils.secure_compare(
  #       ::Digest::SHA256.hexdigest(username),
  #       ::Digest::SHA256.hexdigest(Rails.application.secrets[:sidekiq_username])
  #     ) &
  #       ActiveSupport::SecurityUtils.secure_compare(
  #         ::Digest::SHA256.hexdigest(password),
  #         ::Digest::SHA256.hexdigest(Rails.application.secrets[:sidekiq_password])
  #       )
  #   end
  # end

  # mount Sidekiq::Web, at: '/sidekiq'
end

app/views/pages/data/_confirmation.html.erb
<% if not confirmed?(target) %>
  <sup class="active-info"><%= t '.not_activated' %></sup>

  <%= link_to(t('.activate'), instance_eval("repeat_#{target}_confirmation_path"),
              class: "activate #{target}") %>
<% end %>

app/views/pages/data/_forum.html.erb
<%= content_tag(:li, forum, id: dom_id(forum), class: dom_class(forum)) do %>
  <div class="item">
    <span class="name">
      <%= link_to forum.name.truncate(64), forum.url, target: "_blank", title: t('jump') %>
    </span>

    <%= render 'pages/data/icons', resource: forum %>
  </div>
<% end %>

app/views/pages/data/_header.html.erb
<div class="border-img"></div>
<div class="header">
  <h2><%= title %></h2>
  <%= link_to btn_name, btn_path %>
</div>

app/views/pages/data/_icons.html.erb
<%= link_to('', icon_path(resource, :edit),
            title: t('edit'), class: 'button-edit') %>

<%= link_to('', resource,
            remote: true,
            method: :delete,
            data: { confirm: t(:realy_delete) },
            title: t('destroy'), class: 'button-delete') %>

<%= link_to('', icon_path(resource, :move_up),
            remote: true,
            method: :patch,
            title: t('move.up'), class: 'button-up') %>

<%= link_to('', icon_path(resource, :move_down),
            remote: true,
            method: :patch,
            title: t('move.down'), class: 'button-down') %>

app/views/pages/data/_icons_menu.html.erb
<%= link_to('', 'todo: im_path(:edit, resource)',
            title: t('edit'),
            class: "button-edit button-settings") %>

<%= link_to('', 'todo: resource',
            remote: true,
            method: :delete,
            data: { confirm: I18n.t('view.confirm_question') },
            title: t('destroy'),
            class: "button-delete button-settings") %>

<%= link_to('', 'todo: im_path(:up, resource)',
            remote: true,
            method: :patch,
            title: t('move.up'),
            class: "button-up button-settings") %>

<%= link_to('', 'todo: im_path(:down, resource)',
            remote: true,
            method: :patch,
            title: t('move.down'),
            class: "button-down button-settings") %>

app/views/pages/data/_letter.html.erb
<%= content_tag(:div, letter, id: dom_id(letter), class: dom_class(letter)) do %>

  <div class="letter-settings">
    <span class="title"><%= letter.name.truncate(55) %></span>
    <%= link_to t('add'), new_letter_item_path(letter_id: letter.id), class: "new_letter_item link" %>

    <ul class="list-day">
      <% post_days(letter).each do |abbr| %>
        <li><%= link_to abbr, '' %></li>
      <% end %>
    </ul>

    <span class="active-info time">
      <%= post_time(letter) %>
    </span>

    <%= render 'pages/data/icons', resource: letter %>
  </div>

  <div class="holder">
    <ul class="letter_items">
      <% letter.letter_items.each do |letter_item| %>
        <%= render 'pages/data/letter_item', letter_item: letter_item %>
      <% end %>
    </ul>
  </div>

<% end %>

app/views/pages/data/_letter_item.html.erb
<%= content_tag(:li, letter_item, id: dom_id(letter_item), class: 'letter-settings') do %>
  <div class="item">
    <span class="name">
      <%= link_to letter_item.name.truncate(64), letter_item.url, title: t('jump'), target: "_blank" %>
    </span>

    <%= render 'pages/data/icons', resource: letter_item %>
  </div>
<% end %>

app/views/pages/data/_my_forums.html.erb
<div class="holder">
  <ul class="forums">
    <% current_user.forums.each do |forum| %>
      <%= render 'pages/data/forum', forum: forum %>
    <% end %>
  </ul>
</div>

app/views/pages/data/_my_letters.html.erb
<div class="letters">
  <% current_user.letters.each do |letter| %>
    <%= render 'pages/data/letter', letter: letter %>
  <% end %>
</div>

app/views/pages/data/_my_settings.html.erb
<ul class="info-list user">

  <li>
    <div class="field info">
      <span class="info-name"><%= User.human_attribute_name(:nick) %></span>
      <span class="info-holder"><%= dashed(current_user.nick) %></span>
    </div>
  </li>

  <li>
    <div class="field info">
      <span class="info-name"><%= Account.human_attribute_name(:email) %></span>
      <span class="info-holder"><%= dashed(current_account.email) %></span>
      <%= render 'pages/data/confirmation', target: :email %>
    </div>
  </li>

  <li>
    <div class="field info">
      <span class="info-name"><%= User.human_attribute_name(:jabber) %></span>
      <span class="info-holder"><%= dashed(current_user.jabber) %></span>
      <%= render 'pages/data/confirmation', target: :jabber %>
    </div>
  </li>

  <li>
    <div class="field info">
      <span class="info-name">&nbsp;</span>
      <span class="info-holder"><%= country_tz_lang(current_user) %></span>
    </div>
  </li>

  <li>
    <div class="field info">
      <span class="info-name">Reader</span>
      <span class="info-holder">
        <%= render 'pages/data/status', whose: :reader %>
      </span>
    </div>
  </li>

  <!-- <li>
       <div class="field info">
       <span class="info-name">Mailer</span>
       <span class="info-holder">
       <%= render 'pages/data/status', whose: :mailer %>
       </span>
       </div>
       </li>
     -->
</ul>

app/views/pages/data/_status.html.erb
<%
resource = nil
resource = current_user.reader_set if whose == :reader
resource = current_user.mailer_set if whose == :mailer
%>

<div class="status <%= whose %>">
  <span><%= resource.status %></span>
  <sup>
    <%= link_to( t(:change), instance_eval("change_status_#{whose}_path(resource)"),
      method: :patch,
      remote: true ) %>
  </sup>
</div>