config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  ###
  # Static pages
  #

  controller :pages do
    get 'home'
    get 'help'
    get 'info'
    get 'data'
  end

  ###
  # Account
  #

  get 'register', to: redirect('accounts/new'),  as: :register
  get 'login',    to: redirect('sessions/new'),  as: :login
  get 'logout',   to: 'sessions#destroy',        as: :logout

  resources :accounts, except: %i[index show]

  get 'accounts/confirm_email/:token' =>
      'accounts#confirm_email', as: :confirm_email

  get 'accounts/confirm_jabber/:token' =>
      'accounts#confirm_jabber', as: :confirm_jabber

  get 'accounts/repeat_email_confirmation' =>
      'accounts#repeat_email_confirmation', as: :repeat_email_confirmation

  get 'accounts/repeat_jabber_confirmation' =>
      'accounts#repeat_jabber_confirmation', as: :repeat_jabber_confirmation

  match 'accounts/reset_password' =>
        'accounts#reset_password', via: %i[get post], as: :reset_password

  ###
  # Others
  #

  resources :contacts, only: %i[new create]
  resources :sessions, only: %i[new create destroy]

  get 'locale/change/:lang', to: 'locale#change', as: :change_locale

  resources :forums, except: :show do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :letters, except: :show do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :letter_items, except: :show do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :reader_sets, as: :reader, only: [] do
    member do
      patch :change_status
    end
  end

  resources :mailer_sets, as: :mailer, only: [] do
    member do
      patch :change_status
    end
  end

  ###
  # Sidekiq monitoring
  #

  # TODO
  # require 'sidekiq/web' # TODO: security (password)
  # mount Sidekiq::Web => '/sidekiq'

  # if Rails.env.production? # TODO
  #   Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  #     ActiveSupport::SecurityUtils.secure_compare(
  #       ::Digest::SHA256.hexdigest(username),
  #       ::Digest::SHA256.hexdigest(Rails.application.secrets[:sidekiq_username])
  #     ) &
  #       ActiveSupport::SecurityUtils.secure_compare(
  #         ::Digest::SHA256.hexdigest(password),
  #         ::Digest::SHA256.hexdigest(Rails.application.secrets[:sidekiq_password])
  #       )
  #   end
  # end

  # mount Sidekiq::Web, at: '/sidekiq'
end

app/views/pages/home/_attention.en.html.erb
You can get messages on Email or Jabber. There is a
<%= link_to("Jabber-bot", help_path(anchor: "bote")) %>,
for the last one, which can
<%= link_to("\"spy\" the news", help_path(anchor: "faq_spy")) %>.

app/views/pages/home/_attention.ru.html.erb
Вы можете получать сообщения на Email или Jabber. Для последнего имеется
<%= link_to("Jabber-бот", help_path(anchor: "bote")) %>,
который кроме всего прочего умеет
<%= link_to("\"подсматривать\" новости", help_path(anchor: "faq_spy")) %>.

app/views/pages/home/_attention.uk.html.erb
Ви можете отримувати повідомлення на Email або Jabber. Для останнього маємо
<%= link_to("Jabber-бота", help_path(anchor: "bote")) %>,
який окрім всього іншого вміє
<%= link_to("\"підглядати\" новини", help_path(anchor: "faq_spy")) %>.

app/views/pages/home/_idea.html.erb
<div class="idea">
  <span class="num"><%= idea_num %></span>
  <div class="holder">
    <p><%= render "pages/home/idea#{idea_num}" %></p>
    <%= link_to t('more'), help_path(anchor: help), class: "more" %>
  </div>
</div>

app/views/pages/home/_idea1.en.html.erb
I have got websites which I like and which I read almost every day
(usually in the evenings). That is why I combined their feeds in one
general group and get the updates on my Email on prescribed days and
prescribed time <u><i>in one combined letter</i></u>.

app/views/pages/home/_idea1.ru.html.erb
У меня есть сайты, которые мне нравятся и которые я читаю почти каждый день (обычно
по вечерам). Поэтому я объединил их фиды в одну общую группу и получаю
обновления на Email в заданные дни в заданное время <u><i>одним общим письмом</i></u>.

app/views/pages/home/_idea1.uk.html.erb
В мене є сайти, які мені подобаються і які я читаю майже кожного дня (зазвичай в
вечірній час). Тому я об'єднав їх фіди в одну загальну группу і отримую
оновлення на Email в задані дні в заданий час <u><i>єдиним загальним
листом</i></u>.

app/views/pages/home/_idea2.en.html.erb
Moreover I take part in the life of some forums. The messages about
new posts come to my Jabber. I usually read them during the working
day.

app/views/pages/home/_idea2.ru.html.erb
Кроме этого, я участвую в жизни некоторых форумов. Сообщения о новых
записях в них приходят мне в Jabber. Их я обычно читаю в течении
рабочего дня.

app/views/pages/home/_idea2.uk.html.erb
Окрім того, я приймаю участь в житті деяких форумів. Повідомлення про
нові записи в них надходять мені в Jabber. Їх я зазвичай читаю на
протязі рабочого дня.

app/views/pages/home/_sign_in.html.erb
<div class="holder">
  <%= form_tag sessions_path, method: :post, class: "login-form" do %>
    <h2><%= t('sessions.form.title') %></h2>


    <div class="field">
      <%= label_tag :email, Account.human_attribute_name(:email), class: "valign" %>
      <%= text_field_tag :email, "", id: "login", autofocus: true %>
    </div>


    <div class="field">
      <%= label_tag :password, Account.human_attribute_name(:password), class: "valign" %>
      <%= password_field_tag :password, "", id: "password" %>
    </div>


    <div class="holder">
      <%= link_to t('sessions.form.links.register'), new_account_path, class: "register-link" %>
    </div>


    <div class="holder-button">
      <%= submit_tag t('form.submit') %>
      <%= link_to t('sessions.form.links.forgot_password'), reset_password_path %>
    </div>

  <% end %>
</div>