config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  ###
  # Static pages
  #

  controller :pages do
    get 'home'
    get 'help'
    get 'info'
    get 'data'
  end

  ###
  # Account
  #

  get 'register', to: redirect('accounts/new'),  as: :register
  get 'login',    to: redirect('sessions/new'),  as: :login
  get 'logout',   to: 'sessions#destroy',        as: :logout

  resources :accounts, except: %i[index show]

  get 'accounts/confirm_email/:token' =>
      'accounts#confirm_email', as: :confirm_email

  get 'accounts/confirm_jabber/:token' =>
      'accounts#confirm_jabber', as: :confirm_jabber

  get 'accounts/repeat_email_confirmation' =>
      'accounts#repeat_email_confirmation', as: :repeat_email_confirmation

  get 'accounts/repeat_jabber_confirmation' =>
      'accounts#repeat_jabber_confirmation', as: :repeat_jabber_confirmation

  match 'accounts/reset_password' =>
        'accounts#reset_password', via: %i[get post], as: :reset_password

  ###
  # Others
  #

  resources :contacts, only: %i[new create]
  resources :sessions, only: %i[new create destroy]

  get 'locale/change/:lang', to: 'locale#change', as: :change_locale

  resources :forums, except: :show do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :letters, except: :show do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :letter_items, except: :show do
    member do
      patch :move_up
      patch :move_down
    end
  end

  resources :reader_sets, as: :reader, only: [] do
    member do
      patch :change_status
    end
  end

  resources :mailer_sets, as: :mailer, only: [] do
    member do
      patch :change_status
    end
  end

  ###
  # Sidekiq monitoring
  #

  # TODO
  # require 'sidekiq/web' # TODO: security (password)
  # mount Sidekiq::Web => '/sidekiq'

  # if Rails.env.production? # TODO
  #   Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  #     ActiveSupport::SecurityUtils.secure_compare(
  #       ::Digest::SHA256.hexdigest(username),
  #       ::Digest::SHA256.hexdigest(Rails.application.secrets[:sidekiq_username])
  #     ) &
  #       ActiveSupport::SecurityUtils.secure_compare(
  #         ::Digest::SHA256.hexdigest(password),
  #         ::Digest::SHA256.hexdigest(Rails.application.secrets[:sidekiq_password])
  #       )
  #   end
  # end

  # mount Sidekiq::Web, at: '/sidekiq'
end

app/views/shared/_errors.html.erb
<%# Ошибки в форме %>
<%
errors_in_instance = defined?(instance) &&
  instance&.errors&.any?
%>

<div class="errors">
  <% if errors_in_instance || flash[:alert].present? %>

    <% if Rails.env.test? %>
      <h3><%= t('form.errors') %> :</h3>
    <% end %>

    <ul>

      <% if errors_in_instance %>
        <% instance.errors.full_messages.each do |msg| %>
          <li><%= msg.html_safe %></li>
        <% end %>
      <% end %>


      <% if flash[:alert].present? %>
        <li><%= flash[:alert].html_safe %></li>
      <% end %>

    </ul>

  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="inner-footer">
  <span class="copyright"><%= copyright.html_safe %></span>
  <%= link_to t('footer.contact'), new_contact_path, class: "contact" %>
</div>

app/views/shared/_google_analytics.html.erb
<%# 1. Insert into layout (head section) %>
<%# 2. See asserts/javascript/google_analytics.coffee %>

<% unless Rails.env.development? || Rails.env.test? %>
  <script>
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
   })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

   ga('create', '<%= Rails.application.secrets.google_analytics_key %>', 'auto');
   ga('send', 'pageview');

  </script>
<% end %>

app/views/shared/_header.html.erb
<div class="logo">
  <strong class="image"><%= link_to '', root_path %></strong>
  <span class="slogan"><%= APP::DESCRIPTION %></span>
</div>


<ul class="links">
  <li>
    <% if !signed_in? %>
      <% unless current_page?(controller: 'pages', action: 'home') %>
        <%= link_to t('header.sign_in'), login_path %>
      <% end %>
    <% else %>
      <%= link_to t('header.sign_out'), logout_path %>
    <% end %>
  </li>
  <li>
    <%= link_to t('header.help'), help_path, class: "active" %>
  </li>
</ul>


<ul class="langs">
  <li class="en"><%= render 'shared/lang', name: :en %></li>
  <li class="uk"><%= render 'shared/lang', name: :uk %></li>
  <li class="ru"><%= render 'shared/lang', name: :ru %></li>
</ul>

app/views/shared/_lang.html.erb
<%
title = ''

title = 'English'   if name == :en
title = 'Russian'   if name == :ru
title = 'Ukrainian' if name == :uk
%>

<%= link_to(image_tag("flag-#{name}.gif",
                      width: 42,
                      height: 22,
                      alt: ''),

            change_locale_path(name),
            title: title
) %>

app/views/shared/_submit_tag.html.erb
<%# Засабмитить форму %>
<% val = defined?(text) ? text : t('form.submit') %>

<div class="holder-button">
  <%= submit_tag(val) %>
  <%= yield %> <%# See example in sessions/_form.html.erb %>
</div>

app/views/shared/change_status.js.erb
<% whose = @resource.class == ReaderSet ? :reader : :mailer %>

$('.status.<%= whose %>').
                     html("<%= j render 'pages/data/status', whose: whose %>")

app/views/shared/destroy.js.erb
$("#<%= @resource.class.name.underscore %>_<%= @resource.id %>").remove()

app/views/shared/move_down.js.erb
current = $("#<%= @resource.class.name.underscore %>_<%= @resource.id %>").first()
prev = current.next()

if (current && prev) {
  $(current).insertAfter(prev);
}

app/views/shared/move_up.js.erb
// приходится писать на js, т.к. js.coffee.erb не работает.
// баг здесь: https://github.com/rails/coffee-rails/issues/36

current = $("#<%= @resource.class.name.underscore %>_<%= @resource.id %>").first()
prev = current.prev()

if (current && prev) {
  $(current).insertBefore(prev);
}